# Mario Kart 64 (U) disassembly and split file
# generated by n64split v0.4a - N64 ROM splitter

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64

.include "macros.inc"

.section .text, "ax"

glabel entry_point
# ---- v40 TAIL LOAD (root cause of the "layout landmine", tasks #33/#45): ----
# The IPL3 boot copies EXACTLY 0x100000 bytes (PI_WR_LEN = 0xFFFFF: the
# `addiu 0xFFFF` in boot.s sign-extends) from ROM 0x1000 to 0x80000400, and
# nothing else ever loads the rest of the main segment. Vanilla main fit in
# 1MB; ours outgrew it, so the tail of .data (audio tables — gNoteFrequencies
# et al.) arrived as bss-zeros whenever the layout shifted them past
# 0x80100400: the audio thread then FPEs (0/0) on the first menu jingle and
# the game thread blocks forever on the audio queue. DMA the tail here,
# before ANY game code runs. Clobbers t0-t3 only; polls PI to completion.
.set PI_BASE_K1, 0xA4600000
    lui   $t2, %hi(_mainSegmentEnd)
    addiu $t2, %lo(_mainSegmentEnd)
    lui   $t3, 0x8010
    ori   $t3, $t3, 0x0400            # 0x80100400 = end of the IPL3-loaded 1MB
    subu  $t2, $t2, $t3
    blez  $t2, .Lnp_tail_done         # main fits in 1MB: nothing to load
     lui  $t0, %hi(PI_BASE_K1)
.Lnp_pi_wait1:
    lw    $t1, 0x10($t0)              # PI_STATUS
    andi  $t1, $t1, 0x3               # IO/DMA busy
    bnez  $t1, .Lnp_pi_wait1
     nop
    lui   $t1, 0x0010
    ori   $t1, $t1, 0x0400
    sw    $t1, 0x0($t0)               # PI_DRAM_ADDR = 0x100400 (phys)
    lui   $t1, 0x1010
    ori   $t1, $t1, 0x1000
    sw    $t1, 0x4($t0)               # PI_CART_ADDR = 0x10101000 (ROM 0x101000)
    addiu $t2, $t2, -1
    sw    $t2, 0xC($t0)               # PI_WR_LEN = len-1 -> starts the DMA
.Lnp_pi_wait2:
    lw    $t1, 0x10($t0)
    andi  $t1, $t1, 0x3
    bnez  $t1, .Lnp_pi_wait2
     nop
.Lnp_tail_done:
# ---- original entry: clear bss, set up sp, jump to main_func --------------
/* 001000 80000400 3C08800F */  lui   $t0, %hi(_mainSegmentEnd) # $t0, 0x800f
/* 001004 80000404 3C09000A */  lui   $t1, (0x000A0FC0 >> 16) # lui $t1, 0xa
/* 001008 80000408 25086910 */  addiu $t0, %lo(_mainSegmentEnd) # addiu $t0, $t0, 0x6910
/* 00100C 8000040C 35290FC0 */  ori   $t1, (0x000A0FC0 & 0xFFFF) # ori $t1, $t1, 0xfc0
.L80000410:
/* 001010 80000410 2129FFF8 */  addi  $t1, $t1, -8
/* 001014 80000414 AD000000 */  sw    $zero, ($t0)
/* 001018 80000418 AD000004 */  sw    $zero, 4($t0)
/* 00101C 8000041C 1520FFFC */  bnez  $t1, .L80000410
/* 001020 80000420 21080008 */   addi  $t0, $t0, 8
/* 001024 80000424 3C0A8000 */  lui   $t2, %hi(main_func) # $t2, 0x8000
/* 001028 80000428 3C1D8015 */  lui   $sp, %hi(D_80152300) # $sp, 0x8015
/* 00102C 8000042C 254A0484 */  addiu $t2, %lo(main_func) # addiu $t2, $t2, 0x484
/* 001030 80000430 01400008 */  jr    $t2
/* 001034 80000434 27BD2300 */   addiu $sp, %lo(D_80152300) # addiu $sp, $sp, 0x2300
/* 001038 80000438 00000000 */  nop   
/* 00103C 8000043C 00000000 */  nop   
/* 001040 80000440 00000000 */  nop   
/* 001044 80000444 00000000 */  nop   
/* 001048 80000448 00000000 */  nop   
/* 00104C 8000044C 00000000 */  nop   
